name: Update Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  download-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download File
      run: |
        curl -o data/apispec.json https://www.wolframalpha.com/.well-known/apispec.json

    - name: Commit and Push
      run: |
        git config --local user.email "kubedocker@github.com"
        git config --local user.name "kubedocker"
        git add data/apispec.json
        git commit -m "Update apispec.json"
        git push