name: Update Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  download-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download File
      run: |
        curl -o data/apispec.json https://www.wolframalpha.com/.well-known/apispec.json

    - name: Update resources
      uses: test-room-7/action-update-file@v1
      with:
        # Include all JS files from the `dist` directory
        file-path: data/apispec.json
        commit-msg: Update resources
        github-token: ${{ secrets.K8R_TOKEN }}
